general:
   model_path: ../../../image_classification/experiments_outputs/pruned_quantization/quantized_models/quantized_model.tflite
   global_seed: 127
   
operation_mode: evaluation

dataset:
   training_path: ../datasets/flower_photos
   validation_split: 0.2
   seed: 127

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

mlflow:
   uri: ../../../image_classification/experiments_outputs/mlruns

hydra:
   run:
      dir: ../../../image_classification/experiments_outputs/pruned_evaluation