general:
  logs_dir: logs
  model_path: ../../../image_classification/experiments_outputs/pruned_models/PR_L2_0.6/PR_L2_0.6.h5
  saved_models_dir: saved_models
  display_figures: True
  global_seed: 127
  gpu_memory_limit: null

operation_mode: training

dataset:
  name: flowers
  class_names:
  - daisy
  - dandelion
  - roses
  - sunflowers
  - tulips
  training_path:  ../dataset/flower_photos
  validation_path: null
  validation_split: 0.2
  test_path: null
  quantization_path: null
  quantization_split: null
  seed: 127

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

data_augmentation:
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.2
  random_flip:
    mode: horizontal_and_vertical
  random_translation:
    width_factor: 0.2
    height_factor: 0.2
  random_rotation:
    factor: 0.15
  random_zoom:
    width_factor: 0.25
    height_factor: 0.25

training:
   batch_size: 64
   epochs: 200
   dropout: 0.3
   optimizer:
      Adam:
         learning_rate: 0.001
   callbacks:
      ReduceLROnPlateau:
         monitor: val_accuracy
         factor: 0.5
         patience: 10
      EarlyStopping:
         monitor: val_accuracy
         patience: 40

mlflow:
   uri: ../../../image_classification/experiments_outputs/mlruns

hydra:
   run:
      dir: ../../../image_classification/experiments_outputs/pruned_fine_tuning  
