general:
   model_path: ../../../image_classification/experiments_outputs/pruned_fine_tuning/saved_models/best_model.h5

operation_mode: quantization

dataset:
  name: flowers
  class_names: [daisy, dandelion, roses, sunflowers, tulips]
  quantization_path:  ../datasets/flower_photos
  quantization_split: 0.3
  seed : 127

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

mlflow:
   uri: ../../../image_classification/experiments_outputs/mlruns

hydra:
   run:
      dir: ../../../image_classification/experiments_outputs/pruned_quantization